### ISSUE TITLE
Gets stuck when you paste text into shell (oh-my-posh pure theme)

### ISSUE THREAD

**Issue by brian6932** [digitalguy99/pwsh-syntax-highlighting#2]
Occurs with both shell paste, and terminal paste from alacritty's config
Occurs regardless of whether oh-my-posh is enabled or not
You can't `ctrl+c` out, or even `ctrl+d` to close, you have to close the whole terminal instance

This seems to be specific to alacritty, it doesn't happen when using pwsh directly without a terminal, or when using wezterm

OS: Windows 10
Shell: PowerShell 7.3.0-preview.6
Terminal: alacritty 0.10.1 (2844606)

**Comment by digitalguy99** [comment]
I've never used alacritty before but I don't seem to have this problem. You can try updating your PowerShell or you can try switching over to Windows Terminal.

**Comment by brian6932** [comment]
Try pasting this on latest alacritty with latest pwsh preview (while syntax-highlighting is enabled and imported already):
`Import-Module syntax-highlighting`

**Comment by digitalguy99** [comment]
I just installed alacritty and I tried pasting `Import-Module syntax-highlighting` 
(while syntax-highlighting is enabled and imported already) and I don't seem to run into any problems.

**Comment by brian6932** [comment]
@digitalguy99 after a little more testing, it only seems to happen on the first command sent to the shell, if you do it after it no longer happens

**Comment by brian6932** [comment]
ok no, even that's wrong, if I do it right after the launch of my terminal can reproduce pretty consistently, but sometimes it doesn't show

**Comment by brian6932** [comment]
Not directly after launch, waited a bit: https://i.alienpls.org/xxo.apng
directly after launch: https://i.alienpls.org/kzZ.apng

**Comment by digitalguy99** [comment]
Have you tried changing your `oh-my-posh` theme? Or testing [this](https://github.com/digitalguy99/pwsh-syntax-highlighting#user-content-oh-my-posh-support) solution out?

**Comment by brian6932** [comment]
> Occurs regardless of whether oh-my-posh is enabled or not

**Comment by digitalguy99** [comment]
> > Occurs regardless of whether oh-my-posh is enabled or not

@brian6932 What I'm saying is that, regardless if you are using `oh-my-posh` or not,  [this](https://github.com/digitalguy99/pwsh-syntax-highlighting#user-content-oh-my-posh-support) solution uses a different approach in implementing the syntax-highlighting module. So, I think it'll be worth trying out.

**Comment by brian6932** [comment]
@digitalguy99 yes this seems to fix the issue

**Comment by brian6932** [comment]
Maybe pure shouldn't be marked with a ✅ [here](https://github.com/digitalguy99/pwsh-syntax-highlighting#oh-my-posh-support) then.
So the issue is just that it doesn't play well with the oh-my-posh theme?

**Comment by digitalguy99** [comment]
> Maybe pure shouldn't be marked with a ✅ [here](https://github.com/digitalguy99/pwsh-syntax-highlighting#oh-my-posh-support) then. So the issue is just that it doesn't play well with the oh-my-posh theme?

Yeah, that might be the issue.

**Comment by digitalguy99** [comment]
@brian6932 Thank you for raising this issue, I've marked `pure` with an `❌`.
