### ISSUE TITLE
Issue with unescaped []

### ISSUE THREAD

**Issue by brian6932** [digitalguy99/pwsh-syntax-highlighting#3]
Ok now that I used [this](https://github.com/digitalguy99/pwsh-syntax-highlighting#oh-my-posh-support) method of installation, I encountered a new issue.
https://urlzs.com/rm9d2

**Comment by digitalguy99** [comment]
@brian6932 Sorry for taking very long. I've updated the script. Please give it another try and let me know how it goes.
Thank you in advance.

**Comment by brian6932** [comment]
Seems fixed
